### PR TITLE
build: Adjust names for repo moved out of holding and renamed.

### PR DESCRIPTION
**Pull request by lenny-intel**
Signed-off-by: lenny <leonard.goodell@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
old names are still in import statements , mod file, etc

Issue Number: n/a

## What is the new behavior?
New names now used in import statements , mod file, etc

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ernestojeda — DISMISSED** [review]
LGTM

**Review by ajcasagrande — DISMISSED** [review]
LGTM

**Comment by lenny-intel** [comment]
recheck

**Review by ernestojeda — APPROVED** [review]

**Comment by askb** [comment]
recheck

**Comment by ernestojeda** [comment]
@lenny-intel snapcraft.yaml needs an update as well https://github.com/edgexfoundry/app-rfid-llrp-inventory/blob/main/snap/snapcraft.yaml

**Comment by lenny-intel** [comment]
> snapcraft.yaml needs an update as well

Yea, I meant to check it and forgot. Fixing now.

**Comment by ernestojeda** [comment]
> > snapcraft.yaml needs an update as well
> 
> Yea, I meant to check it and forgot. Fixing now.

yes

**Review by ernestojeda — APPROVED** [review]

**Pull request merged**
